### ISSUE TITLE
Remove deprecated react-tools

### ISSUE THREAD

**Issue by benmccann** [lagom/activator-lagom-java-chirper#56]
`react-tools` was deprecated two years ago. It's recommended that we use babel instead

**Comment by TimMoore** [comment]
@benmccann this was an intentional compromise made to reduce download & compile times... see https://github.com/lagom/activator-lagom-java-chirper/pull/52 and https://github.com/lagom/activator-lagom-java-chirper/issues/54#issuecomment-300334364

Maybe there's another solution? Given #54, I'm starting to wonder if we should pull out React entirely, as grappling with a front-end build stack is pretty superfluous to the point of this project.

**Comment by benmccann** [comment]
`npm install` is a step that only needs to be run once. Installing `babel` takes 10s vs 4s for `react-tools`. An extra 6s once ever on initial setup doesn't seem like much of an issue to me. Am I missing something?

I think that if we switched to babel that it would also fix #54. The way we're using `react-tools` really is not recommended

I prefer vue to react, but nonetheless I think it's really nice to have this project using react. It's very helpful to see how a modern application is structured end-to-end and most applications today use JS frontends and `npm`. Eventhough I chose a different JS framework for my apps, it's still super helpful to me to see the app written with a JS frontend more inline with how I'll actually structure my app. And I don't mind that it's using react instead of the framework I use. React is probably the most popular frontend library today, so it makes perfect sense to have it be the one you'd use in an example

**Comment by ignasi35** [comment]
@benmccann should this be closed then ?

**Comment by benmccann** [comment]
No, I don't think so. Why do you say that?

**Comment by ignasi35** [comment]
>I prefer vue to react, but nonetheless I think it's really nice to have this project using react.

Sorry, I missunderstood. ☺️
